Add missing files to `TinyGSM` library
Trying to compile the sketch yields:

```
/Users/d.mohns/Development/OpenSmartMeter/Firmware code/smart_energy_meter/Library/TinyGSM-0.11.5/src/TinyGsmClient.h:13:10: fatal error: TinyGsmClientSIM800.h: No such file or directory
   13 | #include "TinyGsmClientSIM800.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This adds the missing files.